name: Require 2 Approvals

# Trigger the workflow on PR creation/update and review changes
on:
  pull_request_review:
    types:
      - submitted
      - dismissed

jobs:
  check-approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Check approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request?.number;

            if (!prNumber) {
              core.setFailed("No PR number found.");
              return;
            }

            // List all reviews for the PR
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            // Only keep the latest review from each user
            const latestReviews = new Map();
            for (const review of reviews) {
              latestReviews.set(review.user.login, review.state);
            }

            // Count approvals
            const approvedCount = [...latestReviews.values()].filter(state => state === "APPROVED").length;

            core.info(`Approvals: ${approvedCount}`);

            // Fail if less than 2 approvals
            if (approvedCount < 2) {
              core.setFailed("❌ This PR needs at least 2 approvals before merging.");
            } else {
              core.info("✅ Approval requirement met.");
            }
